=== PolygonAndPixel/eda/xml/likelihood/likelihoods_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="likelihoods">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="likelihood"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="likelihood" maxOccurs="unbounded">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="function_name" type="xs:string"/>
                <xs:element name="lower_bounds" type="xs:string"/>
                <xs:element name="upper_bounds" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PolygonAndPixel/eda/xml/likelihood/all.xml
<?xml version="1.0" encoding="UTF-8"?>
<likelihoods
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="likelihoods_schema.xsd">
    <likelihood>
        <function_name>himmelblau</function_name>
        <lower_bounds>-6 -6</lower_bounds>
        <upper_bounds>6 6</upper_bounds>
    </likelihood>

    <likelihood>
        <function_name>townsend</function_name>
        <lower_bounds>-2.25 -2.5</lower_bounds>
        <upper_bounds>2.5 1.75</upper_bounds>
    </likelihood>

    <likelihood>
        <function_name>rosenbrock</function_name>
        <lower_bounds>-2 -1</lower_bounds>
        <upper_bounds>2 3</upper_bounds>
    </likelihood>

    <likelihood>
        <function_name>eggholder</function_name>
        <lower_bounds>-512 -512</lower_bounds>
        <upper_bounds>512 512</upper_bounds>
    </likelihood>

    <likelihood>
        <function_name>gaussian_shell</function_name>
        <lower_bounds>-6 -6</lower_bounds>
        <upper_bounds>6 6</upper_bounds>
    </likelihood>
</likelihoods>
